### ISSUE TITLE
Make hosting atomic data as easy as possible

### ISSUE THREAD

**Issue by joepio** [joepio/atomic-data-rust#29]
Atomic Data is all about data ownership and control. To do this, we need to make it as _easy as possible_ to host an atomic server somewhere. That's one of the reasons I've picked rust as a language - it compiles to pretty much any target, including WASM. But if we really want to achieve maximum adoption, we need to eliminate as much barriers as possible. There are various approaches to this problem:

## Server ease of use

Make it as simple as possible to run and setup `atomic-server`. Eliminate as much mental energy and time required from the setup process. Make it compatible with most machines. Eliminate runtime dependencies. Provide several options that people are familiar with. Use sensible defaults instead of asking too many questions.

- [x] Docker support #69 
- [x] Docker ARM support #80 
- [x] Atomic-Server compiles to ARM
- [x] Publish pre-built binaries for various targets (this is currently a manual process)
- [ ] Publish to stores (brew / snap / mac app store / windows store / whatever) #117
- [x] GUI all the things
   - [x] Tray icon for desktop #75 
   - [x] Zero-CLI setup (open browser, enter form, you're done) #215 
- [ ] #152 

## Cloudflare Workers + KV

Cloudflare has this really interesting product, called Workers, which lets you run JS and WASM in a serverless context. This means it is way easier to manage than a VPS. It offers storage using [KV](https://developers.cloudflare.com/workers/runtime-apis/kv), which has [no native support for Rust ATM](https://github.com/cloudflare/wrangler/issues/1377), although it can be accessed using wasm-bindgen.

The logic currently present in Atomic-Server is kept as minimal as possible (most resides in atomic-lib), and could probably made in Cloudflare Workers, judging from [this todo example](https://blog.cloudflare.com/building-a-to-do-list-with-workers-and-kv/).

## Running Atomic-Server on a smartphone

https://github.com/joepio/atomic/issues/25

Most people have an old smartphone in a drawer somewhere. These are powerful enough to run atomic-server. So first, we need some way of running it on smartphones. I'd rather not create new swift / java apps for both iOS and android platforms, so I prefer running the existing stuff on Android.

Luckily, atomic-server _does compile to arm_. This should open some possibilities. Couple of ideas:

- Run linux on android (using [gnuroot](https://www.codementor.io/@maxpleaner/run-a-linux-web-server-on-android-device-du1083k05)) 
- Using the android [JNI interface](https://mozilla.github.io/firefox-browser-architecture/experiments/2017-09-21-rust-on-android.html) to interface java - rust.
- Using [flutter + wasm](https://dev.to/sunshine-chain/dart-meets-rust-a-match-made-in-heaven-9f5). Would be ideal (just one codebase to maintain, both for UI and server). Still requires a solution to actix not having WASI compatibility, though.

**Comment by joepio** [comment]
[tauri](https://tauri.studio/en/) is an interesting new way of packaging / bundling desktop apps. 

Most relevant for browser front-ends, though, so [atomic-data-browser](https://github.com/joepio/atomic-data-browser) in this case.

**Comment by joepio** [comment]
Closing this in favor of the milestone https://github.com/joepio/atomic-data-rust/milestone/1
